### ISSUE TITLE
New feature: Load saved annotations from last session

### ISSUE THREAD

**Issue by ChristianIngwersen** [dbaranchuk/human-pose-annotator#1]
Hi, first of all thanks for the great work!
Would it be possible to add a feature to load in saved annotations? In my current setup I need to restart the webserver between sessions meaning that I need to remember which images have been annotated and which still is missing an annotation. 

I have however solved this with a python script that looks in the annotation file and moves all of the annotated images away from the /data folder. But it would be nice just to keep the annotations in the tool which also would allow me to check other people's annotations.

**Comment by dbaranchuk** [comment]
Hi, 

Thanks for your interest and sorry for the late response. I agree that this feature could be very useful. However, unfortunately, I do not maintain this project today.
